### ISSUE TITLE
"Copy Address" button not working

### ISSUE THREAD

**Issue by deerwhisper2310** [greenart7c3/Citrine#11]
In the notification for Citrine, there is a button that says "Copy Address", which I assume should copy the relay URL to my clipboard. This unfortunately isnt happening: when I click the button, nothing is copied. 

- Citrine v0.2.7
- GrapheneOS

**Comment by greenart7c3** [comment]
Fixed in https://github.com/greenart7c3/Citrine/commit/e82d0a176df3df2e41866216054256bb282400d1
