### ISSUE TITLE
Request: Support nip11

### ISSUE THREAD

**Issue by dluvian** [greenart7c3/Citrine#18]
It would be nice if clients could open the relay profile of a citrine instance. Basic fields like `name`, `description`, `software` and `version` are enough.

nip11: https://github.com/nostr-protocol/nips/blob/master/11.md

**Comment by greenart7c3** [comment]
This already works

![Screenshot_20240728-161923.png](https://github.com/user-attachments/assets/b4c36739-f182-40ac-9e23-9539f257837b)

**Comment by dluvian** [comment]
It works indeed. I was just incorrectly formatting the url. Thank you!
