### ISSUE TITLE
Edit server info

It would be nice if we could edit Name, description, owner, software, version, contact.

### ISSUE THREAD

**Issue by Austinati** [greenart7c3/Citrine#29]
![352862373-b4c36739-f182-40ac-9e23-9539f257837b.png](https://github.com/user-attachments/assets/4bb8200e-155e-4e2b-8061-764feb0522c6)

**Comment by Austinati** [comment]
@greenart7c3

**Comment by Austinati** [comment]
This is NIP-11?

**Comment by greenart7c3** [comment]
Yes, it's nip 11

**Comment by Austinati** [comment]
What are your thoughts on this?

**Comment by greenart7c3** [comment]
I'll add support for changing this

**Comment by git-3000** [comment]
sounds like a good idea but possibly keep the Citrine branding somewhere so others can see we are using Citrine and it can become more popular, more downloaded & have more contributors

**Comment by Austinati** [comment]
@greenart7c3 how would I be able to open the code in a code editor. Or what code editor do you use and how do you convert it into an APK?

**Comment by greenart7c3** [comment]
You need android studio.

**Comment by Austinati** [comment]
What files do I import?

**Comment by greenart7c3** [comment]
In the import database button it's a jsonl file
You can get one using backup.greenart7c3.com

**Comment by Austinati** [comment]
Let's continue this in Nostr DM's?

**Comment by greenart7c3** [comment]
Sure

**Comment by Austinati** [comment]
npub1ymtf5f9tq42kq0vp29sfd089x9syfr8ye4k59qx32v748a889hfqyd2h26
