### ISSUE TITLE
Enhancement: Add Notification/Visual Indicator for a Successful Import and Merge of NostrSync Backup Data

### ISSUE THREAD

**Issue by crimsonleaf363** [greenart7c3/Citrine#6]
Related Closed Feature Request: https://github.com/greenart7c3/Citrine/issues/2

## Summary
I would like to have a notification or visual indicator to confirm that my NostrSync backup has been successfully imported and merged.

### Basic example
The user imports their NostrSync backup into Citrine. After the backup data is successfully imported and merged, the user receives a notification or a visual indicator is displayed.

### Motivation
Users can have more confidence that their backup data has been successfully imported and merged.

**Comment by greenart7c3** [comment]
added in version 0.2.7
